### ISSUE TITLE
Deploy tryArrow in each instance for the appropriate arrow version

### ISSUE THREAD

**Issue by dominv** [47deg/try.arrow-kt.io#44]
Deploy tryArrow in each instance for the appropriate arrow version: 
0.8.2
0.9.0

**Comment by dominv** [comment]
Deployed versions:
**0.8.2**:
 - Branch: https://github.com/47deg/try.arrow-kt.io/tree/domin-modifications-for-release-0.8.2
 - Instance: https://3.84.63.125:80

**0.9.0-SNAPSHOT**:
 - Branch: https://github.com/47deg/try.arrow-kt.io/tree/domin-modifications-for-release-0.9.0
 - Instance: https://3.89.54.157:80 (to be used for the 0.9.0, once released)

**Comment by vejeta** [comment]
We must change this to use one instance that will be able to use different arrow versions, specified during runtime.

This can be closed when the alternative solution have been implemented.

**Comment by fedefernandez** [comment]
Related to #52

**Comment by franciscodr** [comment]
Not needed after completing #52
