### ISSUE TITLE
Deploy the docs in each bucket for the appropriate arrow version

### ISSUE THREAD

**Issue by dominv** [47deg/try.arrow-kt.io#45]

**Comment by calvellido** [comment]
When we face this, with the default Try Arrow server for the Playground being https://try.arrow-kt.io:80, for this to connect with the proper Try Arrow instance we need to modify the following:

```diff
- <script src="https://unpkg.com/arrow-playground@1" data-selector="[class^='language-kotlin']"></script>
+ <script src="https://unpkg.com/arrow-playground@1" data-selector="[class^='language-kotlin']" data-server="https://try-082.arrow-kt.io:80"></script>
```

https://github.com/arrow-kt/arrow/blob/d54fe2571b4435158c18c1289754a79a677db60a/modules/docs/arrow-docs/docs/_includes/_js-bottom-docs.html#L4

And then generate the docs.
