### ISSUE TITLE
Disassociate try.arrow-kt.io deployment scripts and necessary files from try-kotlin code

### ISSUE THREAD

**Issue by dominv** [47deg/try.arrow-kt.io#7]

**Comment by dominv** [comment]
Related PRs #24  #25 #26  -> Merged

**Comment by dominv** [comment]
Currently, every time the deploy script is triggered it will take the last changes from try-kotlin's master branch and it will build tryArrow over it. 

My only concern is: What happens if, for some reason, the try-kotlin's master branch causes a broken build? 

@fedefernandez Any ideas about this?

**Comment by fedefernandez** [comment]
I think we should use a specific commit hash for tryKotlin and every time we notice changes, update the commit hash and check if it works. Does it make sense?

**Comment by dominv** [comment]
@fedefernandez I've created the following issues to stablish a safer and automatic deployment process: 
#28 - Use a specific commit hash from tryKotlin
#29 - Automatize the update of the specific commit hash from tryKotlin enhancement
