### ISSUE TITLE
Add deploy_tryarrow script to arrow to deploy a new version of tryarrow when a new version of arrow is published.

### ISSUE THREAD

**Issue by dominv** [47deg/try.arrow-kt.io#8]

**Comment by dominv** [comment]
Created cron job in travis to build master daily https://travis-ci.org/47deg/try.arrow-kt.io/

**Comment by vejeta** [comment]
When the PRs with Github Actions have been merged and the Secrets configured, the deployments will be made whenever master changes in Arrow.
This wouldn't be needed afterwards

**Comment by vejeta** [comment]
These PR have been merged.

https://github.com/arrow-kt/arrow/pull/1570
https://github.com/47deg/try.arrow-kt.io/pull/51/

So there is a tryArrow deployment every merge in arrow's master.

@fedefernandez 
GitHub Actions are still in beta, so we shall we consider maintain this in the meanwhile?
What are the costs of maintaining the travis jobs?
